import chess

def analyze_position(fen_string):
    """
    Takes a text FEN string and uses official chess rules to understand the board state.
    """
    try:
        # 1. Create a "smart" chess board object from our FEN string
        board = chess.Board(fen_string)
        
        # 2. Ask the engine to evaluate the mathematical state of the game
        is_valid = board.is_valid()
        is_check = board.is_check()
        is_checkmate = board.is_checkmate()
        
        # 3. Ask the engine for every legal move the player can make
        legal_moves = [move.uci() for move in board.legal_moves]
        
        return {
            "is_valid": is_valid,
            "turn": "White" if board.turn == chess.WHITE else "Black",
            "in_check": is_check,
            "is_checkmate": is_checkmate,
            "legal_moves_count": len(legal_moves),
            "sample_legal_moves": legal_moves[:5]  # Just show the first 5 so it doesn't flood the JSON
        }
        
    except ValueError as e:
        return {"error": f"Invalid FEN string generated by AI: {e}"}